# Generated by Django 3.1.4 on 2023-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
