# Generated by Django 3.1.4 on 2023-01-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('pregunta', '0002_auto_20230110_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
